### ISSUE TITLE
Not sure if I am dumb

### ISSUE THREAD

**Issue by baschenbrenner** [learn-co-curriculum/python-p3-fileio-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204244?module_item_id=467996

### Concern

When I did this and ran pytest I got the following error.

 def test_write_file():
    
      #Create temp directory to write file to and see if it exits.
      with tempfile.TemporaryDirectory() as tmp_dirname:
        filename = str(uuid.uuid4())
        expected_file_content = str(uuid.uuid4())
        write_file(f'{tmp_dirname}/{filename}',expected_file_content)
>       assert os.path.exists(f'{tmp_dirname}/{filename}.txt') == True
E       AssertionError: assert False == True
E        +  where False = <function exists at 0x1028aa3b0>('/var/folders/_9/w589zxr12zv5p6nhc32fbrfm0000gn/T/tmp7n9lgo5i/872e06e0-9659-46fa-9c4c-8c5b8f97564b.txt')
E        +    where <function exists at 0x1028aa3b0> = <module 'posixpath' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py'>.exists
E        +      where <module 'posixpath' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py'> = os.path

testing/file_io_test.py:14: AssertionError
================================= short test summary info =================================
FAILED module test_write_file - AssertionError: assert False == True

### Additional Context

I was able to show that I could write the three methods and use them making a dummy file called ben.txt and just doing it in my python console so I'm not totally dumb!

**Comment by professor-ben** [comment]
You're definitely not dumb! This is Prabhdip's module though, so I'm going to send it his way.

**Comment by pgill97** [comment]
This may be an environment setup issue. Will look at issue in the near future.
