### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-fileio-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204244?module_item_id=467996

### Concern

It might help students to tell them that they need to add .txt to the filename for the write_file function. It isn't clear that the file_name won't already have that included.

Also, the append_file tests passed as soon as the write_file function was built.

**Comment by pgill3** [comment]
Added to readme
```
The file_name can be a combined file path/name, you will need to add the file extension to the file_name when opening a file.
```
 and changed pipfile to use 3.8.13. Fixed file structure and removed `__init__.py` files.

**Comment by pgill97** [comment]
Resolved append test passes with the write_file function.
