### ISSUE TITLE
Pytest command not found

### ISSUE THREAD

**Issue by darkcohiba** [learn-co-curriculum/python-p3-fileio-lab#6]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204244?module_item_id=467996

### Concern

Tested pytest in the shell and outside the shell, got nothing both ways

`samuelwaters@Samuel-Waters-MacBook-Pro python-p3-fileio-lab % pipenv shell
Launching subshell in virtual environment...
 . /Users/samuelwaters/.local/share/virtualenvs/python-p3-fileio-lab-Gg1rPU4b/bin/activate
samuelwaters@Samuel-Waters-MacBook-Pro python-p3-fileio-lab %  . /Users/samuelwaters/.local/share/virtualenvs/python-p3-fileio-lab-Gg1rP
U4b/bin/activate
(python-p3-fileio-lab) samuelwaters@Samuel-Waters-MacBook-Pro python-p3-fileio-lab % pytest -x
zsh: command not found: pytest
(python-p3-fileio-lab) samuelwaters@Samuel-Waters-MacBook-Pro python-p3-fileio-lab % 
samuelwaters@Samuel-Waters-MacBook-Pro python-p3-fileio-lab % pytest
zsh: command not found: pytest
samuelwaters@Samuel-Waters-MacBook-Pro python-p3-fileio-lab % pytest -x
zsh: command not found: pytest`

**Comment by pgill97** [comment]
Added pytest
