### ISSUE TITLE
.txt file

### ISSUE THREAD

**Issue by DavidWolff218** [learn-co-curriculum/python-p3-fileio-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204244?module_item_id=467996

### Concern

<img width="936" alt="Screen Shot 2022-12-29 at 12 49 13 PM" src="https://user-images.githubusercontent.com/60520496/209996201-126707a0-84f5-4e84-8fab-6c2de5540d40.png">
this is a small thing, but i had to look at the solution branch to know that I needed to use the '.txt' as the file extension. Maybe just a note that that is what they will be expected to use here. There is a lot going on in the past couple labs with this stuff, so I think that could easily be missed.

**Comment by pgill97** [comment]
[5fd940e](https://github.com/learn-co-curriculum/python-p3-fileio-lab/commit/5fd940e447f1ef18ad25587f1e0caf491c4f390b)
